# Generated by Django 6.0.5 on 2026-05-26 12:51

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "titre_fr",
                    models.CharField(max_length=200, null=True, verbose_name="Titre"),
                ),
                (
                    "titre_en",
                    models.CharField(max_length=200, null=True, verbose_name="Titre"),
                ),
                (
                    "titre_it",
                    models.CharField(max_length=200, null=True, verbose_name="Titre"),
                ),
                (
                    "description_fr",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Contenu en français"
                    ),
                ),
                (
                    "description_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Contenu en anglais"
                    ),
                ),
                (
                    "description_it",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Contenu en italien"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="evenements/", verbose_name="Image"),
                ),
                (
                    "image_fr",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="evenements/",
                        verbose_name="Image (FR)",
                    ),
                ),
                (
                    "image_en",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="evenements/",
                        verbose_name="Image (EN)",
                    ),
                ),
                (
                    "image_it",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="evenements/",
                        verbose_name="Image (IT)",
                    ),
                ),
                (
                    "image_fr1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="evenements/",
                        verbose_name="Image 1 (FR)",
                    ),
                ),
                (
                    "image_en2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="evenements/",
                        verbose_name="Image 2 (EN)",
                    ),
                ),
                (
                    "image_it3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="evenements/",
                        verbose_name="Image 3 (IT)",
                    ),
                ),
                ("date_debut", models.DateTimeField(verbose_name="Date de début")),
                ("date_fin", models.DateTimeField(verbose_name="Date de fin")),
                ("est_actif", models.BooleanField(default=False, verbose_name="Actif")),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        max_length=255, verbose_name="Libellé de la question"
                    ),
                ),
                (
                    "libelle_fr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Libellé de la question"
                    ),
                ),
                (
                    "libelle_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Libellé de la question"
                    ),
                ),
                (
                    "libelle_it",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Libellé de la question"
                    ),
                ),
                (
                    "type_question",
                    models.CharField(
                        choices=[
                            ("TC", "Réponse courte"),
                            ("TL", "Paragraphe"),
                            ("CU", "Choix unique"),
                            ("CM", "Choix multiples"),
                            ("LD", "Liste déroulante"),
                            ("DT", "Date"),
                            ("FL", "Fichier"),
                            ("BL", "Oui/Non"),
                        ],
                        max_length=2,
                        verbose_name="Type de question",
                    ),
                ),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        help_text="Séparer les options par des points-virgules (;)",
                        verbose_name="Options pour les choix",
                    ),
                ),
                (
                    "options_fr",
                    models.TextField(
                        blank=True,
                        help_text="Séparer les options par des points-virgules (;)",
                        null=True,
                        verbose_name="Options pour les choix",
                    ),
                ),
                (
                    "options_en",
                    models.TextField(
                        blank=True,
                        help_text="Séparer les options par des points-virgules (;)",
                        null=True,
                        verbose_name="Options pour les choix",
                    ),
                ),
                (
                    "options_it",
                    models.TextField(
                        blank=True,
                        help_text="Séparer les options par des points-virgules (;)",
                        null=True,
                        verbose_name="Options pour les choix",
                    ),
                ),
                (
                    "obligatoire",
                    models.BooleanField(default=True, verbose_name="Obligatoire"),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "aide_texte",
                    models.TextField(blank=True, verbose_name="Texte d'aide"),
                ),
                (
                    "aide_texte_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texte d'aide"
                    ),
                ),
                (
                    "aide_texte_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texte d'aide"
                    ),
                ),
                (
                    "aide_texte_it",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texte d'aide"
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, verbose_name="Nom du questionnaire"
                    ),
                ),
                (
                    "nom_fr",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Nom du questionnaire"
                    ),
                ),
                (
                    "nom_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Nom du questionnaire"
                    ),
                ),
                (
                    "nom_it",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Nom du questionnaire"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "image_fr",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="evenements/",
                        verbose_name="Image (FR)",
                    ),
                ),
                (
                    "image_en",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="evenements/",
                        verbose_name="Image (EN)",
                    ),
                ),
                (
                    "image_it",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="evenements/",
                        verbose_name="Image (IT)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InteretEvenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(max_length=100, verbose_name="Nom complet"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "interesse",
                    models.BooleanField(
                        default=False, verbose_name="Je souhaite participer"
                    ),
                ),
                (
                    "accepte_newsletter",
                    models.BooleanField(
                        default=False,
                        verbose_name="J'accepte de recevoir des informations sur les futurs événements",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evenements.evenement",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription à l'événement",
                "verbose_name_plural": "Inscriptions aux événements",
                "unique_together": {("email", "evenement")},
            },
        ),
        migrations.AddField(
            model_name="evenement",
            name="questionnaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="evenements.questionnaire",
                verbose_name="Questionnaire d'inscription",
            ),
        ),
        migrations.CreateModel(
            name="SectionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre dans la section"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evenements.question",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="SectionQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de la section"),
                ),
                (
                    "nom_fr",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Nom de la section"
                    ),
                ),
                (
                    "nom_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Nom de la section"
                    ),
                ),
                (
                    "nom_it",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Nom de la section"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_it",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        through="evenements.SectionQuestion", to="evenements.question"
                    ),
                ),
            ],
            options={
                "verbose_name": "Section du questionnaire",
                "verbose_name_plural": "Sections du questionnaire",
                "ordering": ["ordre"],
            },
        ),
        migrations.AddField(
            model_name="sectionquestion",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="evenements.sectionquestionnaire",
            ),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="sections",
            field=models.ManyToManyField(to="evenements.sectionquestionnaire"),
        ),
        migrations.CreateModel(
            name="ReponseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.TextField(verbose_name="Réponse")),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reponses/fichiers/",
                        verbose_name="Fichier uploadé",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="evenements.interetevenement",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evenements.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse à une question",
                "verbose_name_plural": "Réponses aux questions",
                "unique_together": {("question", "inscription")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="sectionquestion",
            unique_together={("section", "question")},
        ),
    ]
