# Generated by Django 6.0.5 on 2026-05-26 12:51

import django.db.models.deletion
import django_countries.fields
import marketplace.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "name_fr",
                    models.CharField(max_length=100, null=True, verbose_name="Nom"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, null=True, verbose_name="Nom"),
                ),
                (
                    "name_it",
                    models.CharField(max_length=100, null=True, verbose_name="Nom"),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CronTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("validate_products", "Validate Products"),
                            (
                                "check_product_descriptions",
                                "Check Product Descriptions",
                            ),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "name_fr",
                    models.CharField(max_length=100, null=True, verbose_name="Nom"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, null=True, verbose_name="Nom"),
                ),
                (
                    "name_it",
                    models.CharField(max_length=100, null=True, verbose_name="Nom"),
                ),
            ],
            options={
                "verbose_name": "Sous-catégorie",
                "verbose_name_plural": "Sous-catégories",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "reference",
                    models.CharField(
                        default=marketplace.models.generate_reference,
                        editable=False,
                        max_length=15,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom complet du produit (requis pour vente/achat)",
                        max_length=100,
                        null=True,
                        verbose_name="Nom du produit",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titre")),
                (
                    "title_fr",
                    models.CharField(max_length=100, null=True, verbose_name="Titre"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=100, null=True, verbose_name="Titre"),
                ),
                (
                    "title_it",
                    models.CharField(max_length=100, null=True, verbose_name="Titre"),
                ),
                (
                    "description",
                    models.TextField(default="Description", verbose_name="Description"),
                ),
                (
                    "description_fr",
                    models.TextField(
                        default="Description", null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        default="Description", null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_it",
                    models.TextField(
                        default="Description", null=True, verbose_name="Description"
                    ),
                ),
                (
                    "caracteristiques",
                    models.TextField(
                        blank=True,
                        default="Caractéristiques ou spécifications",
                        null=True,
                        verbose_name="Les caractéristiques ou spécifications techniques des produits",
                    ),
                ),
                (
                    "caracteristiques_fr",
                    models.TextField(
                        blank=True,
                        default="Caractéristiques ou spécifications",
                        null=True,
                        verbose_name="Les caractéristiques ou spécifications techniques des produits",
                    ),
                ),
                (
                    "caracteristiques_en",
                    models.TextField(
                        blank=True,
                        default="Caractéristiques ou spécifications",
                        null=True,
                        verbose_name="Les caractéristiques ou spécifications techniques des produits",
                    ),
                ),
                (
                    "caracteristiques_it",
                    models.TextField(
                        blank=True,
                        default="Caractéristiques ou spécifications",
                        null=True,
                        verbose_name="Les caractéristiques ou spécifications techniques des produits",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="announcements/default-product.jpg",
                        help_text="Image illustrative (optionnelle) les dimenssion de l'image doivent être lon:740 px et hau:380 px",
                        null=True,
                        upload_to="announcements/%Y/%m/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vente", "Vente"),
                            ("achat", "Achat"),
                            ("autre", "Autre"),
                        ],
                        default="vente",
                        max_length=20,
                        verbose_name="Type d'annonce",
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Marque"),
                ),
                (
                    "brand_fr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Marque"
                    ),
                ),
                (
                    "brand_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Marque"
                    ),
                ),
                (
                    "brand_it",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Marque"
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Variété"
                    ),
                ),
                (
                    "variety_fr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Variété"
                    ),
                ),
                (
                    "variety_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Variété"
                    ),
                ),
                (
                    "variety_it",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Variété"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantité disponible ou requise",
                        null=True,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="kg, litre, pièce, etc.",
                        max_length=20,
                        verbose_name="Unité de mesure",
                    ),
                ),
                (
                    "unit_fr",
                    models.CharField(
                        blank=True,
                        help_text="kg, litre, pièce, etc.",
                        max_length=20,
                        null=True,
                        verbose_name="Unité de mesure",
                    ),
                ),
                (
                    "unit_en",
                    models.CharField(
                        blank=True,
                        help_text="kg, litre, pièce, etc.",
                        max_length=20,
                        null=True,
                        verbose_name="Unité de mesure",
                    ),
                ),
                (
                    "unit_it",
                    models.CharField(
                        blank=True,
                        help_text="kg, litre, pièce, etc.",
                        max_length=20,
                        null=True,
                        verbose_name="Unité de mesure",
                    ),
                ),
                (
                    "is_organic",
                    models.BooleanField(
                        default=False, verbose_name="Agriculture biologique"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True,
                        help_text="Pays concerné par l'annonce",
                        max_length=2,
                        verbose_name="Pays",
                    ),
                ),
                (
                    "shipping_conditions",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Conditions d'expédition",
                    ),
                ),
                (
                    "shipping_conditions_fr",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Conditions d'expédition",
                    ),
                ),
                (
                    "shipping_conditions_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Conditions d'expédition",
                    ),
                ),
                (
                    "shipping_conditions_it",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Conditions d'expédition",
                    ),
                ),
                (
                    "transaction_details",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Détails de transaction",
                    ),
                ),
                (
                    "transaction_details_fr",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Détails de transaction",
                    ),
                ),
                (
                    "transaction_details_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Détails de transaction",
                    ),
                ),
                (
                    "transaction_details_it",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Détails de transaction",
                    ),
                ),
                (
                    "restrictions",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Restrictions"
                    ),
                ),
                (
                    "restrictions_fr",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Restrictions",
                    ),
                ),
                (
                    "restrictions_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Restrictions",
                    ),
                ),
                (
                    "restrictions_it",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Restrictions",
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending_first", "En attente première validation"),
                            ("pending_second", "En attente seconde validation"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("expired", "Expiré"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "first_approval_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date de première validation",
                    ),
                ),
                (
                    "second_approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de seconde validation"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Raison du rejet"
                    ),
                ),
                (
                    "first_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first_approved_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Premier validateur",
                    ),
                ),
                (
                    "second_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second_approved_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Second validateur",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Mots-clés séparés par des virgules",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Mots-clés",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="marketplace.category",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="marketplace.subcategory",
                        verbose_name="Sous-catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-publication_date"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True, to="marketplace.subcategory", verbose_name="Sous-catégories"
            ),
        ),
        migrations.CreateModel(
            name="AnnouncementView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("ip_address", models.CharField(blank=True, max_length=40)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="marketplace.announcement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vue d'annonce",
                "verbose_name_plural": "Vues d'annonces",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("announcement", "ip_address", "session_key"),
                        name="unique_view_per_session",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["status", "is_archived", "publication_date"],
                name="marketplace_status_5d2492_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["type", "country"], name="marketplace_type_9f4ec0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["reference"], name="marketplace_referen_e01880_idx"
            ),
        ),
    ]
