# Generated by Django 6.0.5 on 2026-05-26 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="societe",
            name="produits_recherches",
            field=models.ManyToManyField(
                blank=True,
                related_name="societes_acheteuses",
                to="marketplace.category",
                verbose_name="Produits recherchés",
            ),
        ),
        migrations.AddField(
            model_name="societe",
            name="produits_vendus",
            field=models.ManyToManyField(
                blank=True,
                related_name="societes_vendeuses",
                to="marketplace.category",
                verbose_name="Produits vendus",
            ),
        ),
        migrations.AddField(
            model_name="societe",
            name="utilisateur",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="societe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
