# Generated by Django 6.0.5 on 2026-07-01 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 ⭐"),
                            (2, "2 ⭐"),
                            (3, "3 ⭐"),
                            (4, "4 ⭐"),
                            (5, "5 ⭐"),
                        ],
                        default=5,
                        verbose_name="Étoiles",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=800, verbose_name="Commentaire"
                    ),
                ),
                (
                    "would_recommend",
                    models.BooleanField(default=True, verbose_name="Recommande"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ratings",
                        to="marketplace.announcement",
                        verbose_name="Annonce concernée",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note vendeur",
                "verbose_name_plural": "Notes vendeurs",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seller", "author", "announcement"),
                        name="unique_rating_per_transaction",
                    )
                ],
            },
        ),
    ]
