# Generated by Django 6.0.5 on 2026-07-24 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_supportmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("message", "Message"),
                            ("announcement", "Annonce"),
                            ("review", "Avis"),
                            ("system", "Système"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "body",
                    models.TextField(blank=True, default="", verbose_name="Détail"),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="Lien"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lue")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="accounts_no_user_id_a4ff2e_idx",
                    )
                ],
            },
        ),
    ]
