# Generated by Django 6.0.5 on 2026-05-26 12:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Titre"
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Titre"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Titre"
                    ),
                ),
                (
                    "title_it",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Titre"
                    ),
                ),
                (
                    "description_fr",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Contenu en français"
                    ),
                ),
                (
                    "description_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Contenu en anglais"
                    ),
                ),
                (
                    "description_it",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Contenu en italien"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/about",
                        verbose_name="picture",
                    ),
                ),
                (
                    "archive",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="archive "
                    ),
                ),
                ("createdat", models.DateTimeField(auto_now_add=True, null=True)),
                ("updateDate", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "À Propos",
                "verbose_name_plural": "À Propos de nous",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archive",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="archive "
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("createdat", models.DateTimeField(auto_now_add=True, null=True)),
                ("updateDate", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("attachment", models.FileField(upload_to="messages/files/")),
                ("image", models.ImageField(upload_to="messages/images/")),
                (
                    "archive",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="archive "
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("edited", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("createdat", models.DateTimeField(auto_now_add=True, null=True)),
                ("updateDate", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="Partenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom du partenaire"),
                ),
                (
                    "logo",
                    models.ImageField(
                        upload_to="media/partenaires/", verbose_name="Logo"
                    ),
                ),
                (
                    "archive",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="archive "
                    ),
                ),
                ("createdat", models.DateTimeField(auto_now_add=True, null=True)),
                ("updateDate", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom de l'ONG",
                    ),
                ),
                (
                    "titre_fr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom de l'ONG",
                    ),
                ),
                (
                    "titre_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom de l'ONG",
                    ),
                ),
                (
                    "titre_it",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom de l'ONG",
                    ),
                ),
                (
                    "phone1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Téléphone 1",
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Téléphone 2",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "description_fr",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Contenu en français"
                    ),
                ),
                (
                    "description_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Contenu en anglais"
                    ),
                ),
                (
                    "description_it",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Contenu en italien"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/presentation/", verbose_name="image"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        upload_to="media/presentation/", verbose_name="Logo"
                    ),
                ),
                (
                    "archive",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="archive "
                    ),
                ),
                ("createdat", models.DateTimeField(auto_now_add=True, null=True)),
                ("updateDate", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Presentation",
                "verbose_name_plural": "Presentations",
                "ordering": ["titre"],
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Titre"
                    ),
                ),
                (
                    "titre_fr",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Titre"
                    ),
                ),
                (
                    "titre_en",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Titre"
                    ),
                ),
                (
                    "titre_it",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Titre"
                    ),
                ),
                (
                    "description_fr",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Contenu en français"
                    ),
                ),
                (
                    "description_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Contenu en anglais"
                    ),
                ),
                (
                    "description_it",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Contenu en italien"
                    ),
                ),
                (
                    "image_fr",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/slide/",
                        verbose_name="Image (FR)",
                    ),
                ),
                (
                    "image_en",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/slide/",
                        verbose_name="Image (EN)",
                    ),
                ),
                (
                    "image_it",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/slide/",
                        verbose_name="Image (IT)",
                    ),
                ),
                (
                    "archive",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="archive "
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Ulr"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name": "Slide",
                "verbose_name_plural": "Slides",
                "ordering": ["titre"],
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom du Sponsor"),
                ),
                (
                    "logo",
                    models.ImageField(upload_to="media/Sponsor/", verbose_name="Logo"),
                ),
                (
                    "archive",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="archive Sponsor ",
                    ),
                ),
                ("createdat", models.DateTimeField(auto_now_add=True, null=True)),
                ("updateDate", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ["nom"],
            },
        ),
    ]
