# Generated by Django 6.0.5 on 2026-06-01 09:19

import idamarketplace.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="messages/files/",
                validators=[idamarketplace.security.validate_document_upload],
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="messages/images/",
                validators=[idamarketplace.security.validate_image_upload],
            ),
        ),
    ]
