# Generated by Django 6.0.5 on 2026-07-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_message_attachment_alter_message_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="À propos de Agri Market Africa",
                        max_length=200,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        default="À propos de Agri Market Africa",
                        max_length=200,
                        null=True,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        default="À propos de Agri Market Africa",
                        max_length=200,
                        null=True,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "title_it",
                    models.CharField(
                        default="À propos de Agri Market Africa",
                        max_length=200,
                        null=True,
                        verbose_name="Titre",
                    ),
                ),
                ("intro", models.TextField(verbose_name="Introduction")),
                ("intro_fr", models.TextField(null=True, verbose_name="Introduction")),
                ("intro_en", models.TextField(null=True, verbose_name="Introduction")),
                ("intro_it", models.TextField(null=True, verbose_name="Introduction")),
                (
                    "vision_title",
                    models.CharField(
                        default="Notre vision",
                        max_length=200,
                        verbose_name="Titre — Vision",
                    ),
                ),
                (
                    "vision_title_fr",
                    models.CharField(
                        default="Notre vision",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Vision",
                    ),
                ),
                (
                    "vision_title_en",
                    models.CharField(
                        default="Notre vision",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Vision",
                    ),
                ),
                (
                    "vision_title_it",
                    models.CharField(
                        default="Notre vision",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Vision",
                    ),
                ),
                ("vision", models.TextField(verbose_name="Notre vision")),
                ("vision_fr", models.TextField(null=True, verbose_name="Notre vision")),
                ("vision_en", models.TextField(null=True, verbose_name="Notre vision")),
                ("vision_it", models.TextField(null=True, verbose_name="Notre vision")),
                (
                    "perspectives_title",
                    models.CharField(
                        default="Nos perspectives d'avenir",
                        max_length=200,
                        verbose_name="Titre — Perspectives",
                    ),
                ),
                (
                    "perspectives_title_fr",
                    models.CharField(
                        default="Nos perspectives d'avenir",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Perspectives",
                    ),
                ),
                (
                    "perspectives_title_en",
                    models.CharField(
                        default="Nos perspectives d'avenir",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Perspectives",
                    ),
                ),
                (
                    "perspectives_title_it",
                    models.CharField(
                        default="Nos perspectives d'avenir",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Perspectives",
                    ),
                ),
                (
                    "perspectives",
                    models.TextField(verbose_name="Nos perspectives d'avenir"),
                ),
                (
                    "perspectives_fr",
                    models.TextField(
                        null=True, verbose_name="Nos perspectives d'avenir"
                    ),
                ),
                (
                    "perspectives_en",
                    models.TextField(
                        null=True, verbose_name="Nos perspectives d'avenir"
                    ),
                ),
                (
                    "perspectives_it",
                    models.TextField(
                        null=True, verbose_name="Nos perspectives d'avenir"
                    ),
                ),
                (
                    "values_title",
                    models.CharField(
                        default="Nos valeurs",
                        max_length=200,
                        verbose_name="Titre — Valeurs",
                    ),
                ),
                (
                    "values_title_fr",
                    models.CharField(
                        default="Nos valeurs",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Valeurs",
                    ),
                ),
                (
                    "values_title_en",
                    models.CharField(
                        default="Nos valeurs",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Valeurs",
                    ),
                ),
                (
                    "values_title_it",
                    models.CharField(
                        default="Nos valeurs",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Valeurs",
                    ),
                ),
                (
                    "mission_title",
                    models.CharField(
                        default="Notre mission",
                        max_length=200,
                        verbose_name="Titre — Mission",
                    ),
                ),
                (
                    "mission_title_fr",
                    models.CharField(
                        default="Notre mission",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Mission",
                    ),
                ),
                (
                    "mission_title_en",
                    models.CharField(
                        default="Notre mission",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Mission",
                    ),
                ),
                (
                    "mission_title_it",
                    models.CharField(
                        default="Notre mission",
                        max_length=200,
                        null=True,
                        verbose_name="Titre — Mission",
                    ),
                ),
                ("mission", models.TextField(verbose_name="Notre mission")),
                (
                    "mission_fr",
                    models.TextField(null=True, verbose_name="Notre mission"),
                ),
                (
                    "mission_en",
                    models.TextField(null=True, verbose_name="Notre mission"),
                ),
                (
                    "mission_it",
                    models.TextField(null=True, verbose_name="Notre mission"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("createdat", models.DateTimeField(auto_now_add=True, null=True)),
                ("updateDate", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Page À propos",
                "verbose_name_plural": "Page À propos",
            },
        ),
        migrations.CreateModel(
            name="AboutValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="Sparkles",
                        help_text="Nom d'icône lucide-react (ex: Award, Leaf, Users, Lightbulb, ShieldCheck).",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titre")),
                (
                    "title_fr",
                    models.CharField(max_length=100, null=True, verbose_name="Titre"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=100, null=True, verbose_name="Titre"),
                ),
                (
                    "title_it",
                    models.CharField(max_length=100, null=True, verbose_name="Titre"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_fr",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_it",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="blog.aboutpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur",
                "verbose_name_plural": "Valeurs",
                "ordering": ["order", "id"],
            },
        ),
    ]
